// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Persistence.Data.Migrations
{
    [DbContext(typeof(DotNetFarmaContext))]
    partial class DotNetFarmaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.Arl", b =>
                {
                    b.Property<int>("ArlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ArlId");

                    b.ToTable("arl", (string)null);

                    b.HasData(
                        new
                        {
                            ArlId = 1,
                            Direccion = "calle 14 # 24-10",
                            Email = "CajasanAyuda@gmail.com",
                            Nombre = "Cajasan",
                            Telefono = "60793820"
                        },
                        new
                        {
                            ArlId = 2,
                            Direccion = "Calle 10 #30-45",
                            Email = "contacto@saludtotal.com",
                            Nombre = "SaludTotal",
                            Telefono = "601234567"
                        },
                        new
                        {
                            ArlId = 3,
                            Direccion = "Av. 5 #18-22",
                            Email = "info@cafesalud.com",
                            Nombre = "Cafesalud",
                            Telefono = "601112233"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Cargo", b =>
                {
                    b.Property<int>("CargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CargoId");

                    b.ToTable("Cargo", (string)null);

                    b.HasData(
                        new
                        {
                            CargoId = 1,
                            Descripcion = "Se encarga de atender en la farmacia",
                            Nombre = "Auxiliar de farmacia"
                        },
                        new
                        {
                            CargoId = 2,
                            Descripcion = "Brinda cuidados médicos a los pacientes",
                            Nombre = "Enfermera"
                        },
                        new
                        {
                            CargoId = 3,
                            Descripcion = "Maneja las finanzas de la empresa",
                            Nombre = "Contador"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ciudad", b =>
                {
                    b.Property<int>("CiudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CiudadId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("ciudad", (string)null);

                    b.HasData(
                        new
                        {
                            CiudadId = 1,
                            DepartamentoId = 1,
                            Nombre = "Bucarmanga"
                        },
                        new
                        {
                            CiudadId = 2,
                            DepartamentoId = 2,
                            Nombre = "Lima"
                        },
                        new
                        {
                            CiudadId = 3,
                            DepartamentoId = 3,
                            Nombre = "Buenos Aires"
                        },
                        new
                        {
                            CiudadId = 5,
                            DepartamentoId = 5,
                            Nombre = "Bogotá"
                        },
                        new
                        {
                            CiudadId = 4,
                            DepartamentoId = 4,
                            Nombre = "Cúcuta"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Compra", b =>
                {
                    b.Property<int>("CompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("date");

                    b.Property<int?>("MedicamentoId")
                        .HasColumnType("int");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("CompraId");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Compra", (string)null);

                    b.HasData(
                        new
                        {
                            CompraId = 1,
                            Cantidad = 200,
                            FechaCompra = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 200000,
                            ProveedorId = 1
                        },
                        new
                        {
                            CompraId = 2,
                            Cantidad = 150,
                            FechaCompra = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 180000,
                            ProveedorId = 2
                        },
                        new
                        {
                            CompraId = 3,
                            Cantidad = 100,
                            FechaCompra = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 150000,
                            ProveedorId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("DepartamentoId");

                    b.HasIndex("PaisId");

                    b.ToTable("departamento", (string)null);

                    b.HasData(
                        new
                        {
                            DepartamentoId = 1,
                            Nombre = "Santander",
                            PaisId = 1
                        },
                        new
                        {
                            DepartamentoId = 2,
                            Nombre = "Lima",
                            PaisId = 2
                        },
                        new
                        {
                            DepartamentoId = 3,
                            Nombre = "Buenos Aires",
                            PaisId = 3
                        },
                        new
                        {
                            DepartamentoId = 4,
                            Nombre = "Norte de Santanader",
                            PaisId = 1
                        },
                        new
                        {
                            DepartamentoId = 5,
                            Nombre = "Cundinamarca",
                            PaisId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ArlId")
                        .HasColumnType("int");

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("EpsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("ArlId");

                    b.HasIndex("CargoId");

                    b.HasIndex("CiudadId");

                    b.HasIndex("EpsId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Empleado", (string)null);

                    b.HasData(
                        new
                        {
                            EmpleadoId = 1,
                            Apellidos = "Escalante",
                            ArlId = 1,
                            CargoId = 1,
                            CiudadId = 1,
                            Direccion = "Cra 33 #48-3",
                            EpsId = 1,
                            FechaContratacion = new DateTime(2011, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Jorge",
                            Telefono = "3294902231",
                            UsuarioId = 0
                        },
                        new
                        {
                            EmpleadoId = 2,
                            Apellidos = "López",
                            ArlId = 2,
                            CargoId = 2,
                            CiudadId = 2,
                            Direccion = "Cra 18 #45-6",
                            EpsId = 2,
                            FechaContratacion = new DateTime(2015, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "María",
                            Telefono = "3209876543",
                            UsuarioId = 0
                        },
                        new
                        {
                            EmpleadoId = 3,
                            Apellidos = "Perez",
                            ArlId = 3,
                            CargoId = 3,
                            CiudadId = 3,
                            Direccion = "Av. 3 #8-15",
                            EpsId = 3,
                            FechaContratacion = new DateTime(2019, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Juan",
                            Telefono = "3101234567",
                            UsuarioId = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Eps", b =>
                {
                    b.Property<int>("EpsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("EpsId");

                    b.ToTable("eps", (string)null);

                    b.HasData(
                        new
                        {
                            EpsId = 1,
                            Direccion = "Calle 49 #43-2",
                            Email = "AtencionAlCliente@avanzar.co",
                            Nombre = "Avanzar",
                            Telefono = "60783822"
                        },
                        new
                        {
                            EpsId = 2,
                            Direccion = "Cra 15 #22-10",
                            Email = "atencion@coomeva.com",
                            Nombre = "Coomeva",
                            Telefono = "601987654"
                        },
                        new
                        {
                            EpsId = 3,
                            Direccion = "Av. 8 #12-30",
                            Email = "info@famisanar.com",
                            Nombre = "Famisanar",
                            Telefono = "601876543"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Medicamento", b =>
                {
                    b.Property<int>("MedicamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("Precio")
                        .HasColumnType("double");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("MedicamentoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("medicamento", (string)null);

                    b.HasData(
                        new
                        {
                            MedicamentoId = 1,
                            FechaExpiracion = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Paracetamol",
                            Precio = 2500.0,
                            ProveedorId = 1,
                            Stock = 150
                        },
                        new
                        {
                            MedicamentoId = 3,
                            FechaExpiracion = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Aspirina",
                            Precio = 2000.0,
                            ProveedorId = 3,
                            Stock = 75
                        },
                        new
                        {
                            MedicamentoId = 2,
                            FechaExpiracion = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ibuprofeno",
                            Precio = 3000.0,
                            ProveedorId = 2,
                            Stock = 100
                        });
                });

            modelBuilder.Entity("Domain.Entities.MedicamentoCompra", b =>
                {
                    b.Property<int>("MedicamentoCompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadComprada")
                        .HasColumnType("int");

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioCompra")
                        .HasPrecision(10, 5)
                        .HasColumnType("decimal(10,5)");

                    b.HasKey("MedicamentoCompraId");

                    b.HasIndex("CompraId");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("table_name", (string)null);

                    b.HasData(
                        new
                        {
                            MedicamentoCompraId = 1,
                            CantidadComprada = 5000,
                            CompraId = 1,
                            MedicamentoId = 1,
                            PrecioCompra = 29383.29m
                        },
                        new
                        {
                            MedicamentoCompraId = 2,
                            CantidadComprada = 2000,
                            CompraId = 2,
                            MedicamentoId = 2,
                            PrecioCompra = 4583.29m
                        },
                        new
                        {
                            MedicamentoCompraId = 3,
                            CantidadComprada = 100,
                            CompraId = 3,
                            MedicamentoId = 3,
                            PrecioCompra = 57893.29m
                        });
                });

            modelBuilder.Entity("Domain.Entities.MedicamentoVenta", b =>
                {
                    b.Property<int>("MedicamentoVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadVendida")
                        .HasColumnType("int");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(10, 5)
                        .HasColumnType("decimal(10,5)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("MedicamentoVentaId");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("VentaId");

                    b.ToTable("medicamento_venta", (string)null);

                    b.HasData(
                        new
                        {
                            MedicamentoVentaId = 1,
                            CantidadVendida = 200,
                            MedicamentoId = 1,
                            PrecioVenta = 29383.29m,
                            VentaId = 1
                        },
                        new
                        {
                            MedicamentoVentaId = 2,
                            CantidadVendida = 1000,
                            MedicamentoId = 2,
                            PrecioVenta = 4583.29m,
                            VentaId = 2
                        },
                        new
                        {
                            MedicamentoVentaId = 3,
                            CantidadVendida = 50,
                            MedicamentoId = 3,
                            PrecioVenta = 57893.29m,
                            VentaId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PacienteId");

                    b.ToTable("paciente", (string)null);

                    b.HasData(
                        new
                        {
                            PacienteId = 1,
                            Apellidos = "Alvarez",
                            Direccion = "Cra 19 #8-45 Barrio Comuneros",
                            Nombre = "Sofia",
                            Telefono = "3224243429"
                        },
                        new
                        {
                            PacienteId = 2,
                            Apellidos = "Gomez",
                            Direccion = "Cra 25 #12-34 Barrio Los Pinos",
                            Nombre = "Carlos",
                            Telefono = "3225556677"
                        },
                        new
                        {
                            PacienteId = 3,
                            Apellidos = "Ramirez",
                            Direccion = "Av. 4 #9-56 Barrio San Martin",
                            Nombre = "Laura",
                            Telefono = "3117778899"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Pais", b =>
                {
                    b.Property<int>("PaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("PaisId");

                    b.ToTable("pais", (string)null);

                    b.HasData(
                        new
                        {
                            PaisId = 1,
                            Nombre = "Colombia"
                        },
                        new
                        {
                            PaisId = 2,
                            Nombre = "Perú"
                        },
                        new
                        {
                            PaisId = 3,
                            Nombre = "Argentina"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ProveedorId");

                    b.ToTable("proveedor", (string)null);

                    b.HasData(
                        new
                        {
                            ProveedorId = 1,
                            Direccion = "Cra 19 # 839",
                            Email = "ProveedorA@gmail.com",
                            Nombre = "ProveedorA",
                            Telefono = "032238492"
                        },
                        new
                        {
                            ProveedorId = 2,
                            Direccion = "Cra 22 # 839",
                            Email = "ProveedorB@gmail.com",
                            Nombre = "ProveedorB",
                            Telefono = "032238493"
                        },
                        new
                        {
                            ProveedorId = 3,
                            Direccion = "Calle 14 # 839",
                            Email = "ProveedorC@gmail.com",
                            Nombre = "ProveedorC",
                            Telefono = "032238494"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("Revocado")
                        .HasColumnType("date");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RolId");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime");

                    b.Property<int?>("MedicamentoId")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("VentaId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("venta", (string)null);

                    b.HasData(
                        new
                        {
                            VentaId = 1,
                            EmpleadoId = 1,
                            FechaVenta = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PacienteId = 1
                        },
                        new
                        {
                            VentaId = 2,
                            EmpleadoId = 2,
                            FechaVenta = new DateTime(2023, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PacienteId = 2
                        },
                        new
                        {
                            VentaId = 3,
                            EmpleadoId = 3,
                            FechaVenta = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PacienteId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ciudad", b =>
                {
                    b.HasOne("Domain.Entities.Departamento", "Departamento")
                        .WithMany("Ciudades")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Domain.Entities.Compra", b =>
                {
                    b.HasOne("Domain.Entities.Medicamento", null)
                        .WithMany("Compras")
                        .HasForeignKey("MedicamentoId");

                    b.HasOne("Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Domain.Entities.Departamento", b =>
                {
                    b.HasOne("Domain.Entities.Pais", "Pais")
                        .WithMany("Departamentos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Domain.Entities.Empleado", b =>
                {
                    b.HasOne("Domain.Entities.Arl", "Arl")
                        .WithMany("Empleados")
                        .HasForeignKey("ArlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Cargo", "Cargo")
                        .WithMany("Empleados")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Ciudad", "Ciudad")
                        .WithMany("Empleados")
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Eps", "Eps")
                        .WithMany("Empleados")
                        .HasForeignKey("EpsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithOne("UsuarioDeEmpleado")
                        .HasForeignKey("Domain.Entities.Empleado", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arl");

                    b.Navigation("Cargo");

                    b.Navigation("Ciudad");

                    b.Navigation("Eps");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Medicamento", b =>
                {
                    b.HasOne("Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("Medicamentos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Domain.Entities.MedicamentoCompra", b =>
                {
                    b.HasOne("Domain.Entities.Compra", "Compra")
                        .WithMany("MedicamentoCompras")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Medicamento", "Medicamento")
                        .WithMany("MedicamentoCompras")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("Domain.Entities.MedicamentoVenta", b =>
                {
                    b.HasOne("Domain.Entities.Medicamento", "Medicamento")
                        .WithMany("MedicamentoVentas")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Venta", "Venta")
                        .WithMany("MedicamentoVentas")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Domain.Entities.Venta", b =>
                {
                    b.HasOne("Domain.Entities.Empleado", "Empleado")
                        .WithMany("Ventas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Medicamento", null)
                        .WithMany("Ventas")
                        .HasForeignKey("MedicamentoId");

                    b.HasOne("Domain.Entities.Paciente", "Paciente")
                        .WithMany("Ventas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Domain.Entities.Arl", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Domain.Entities.Cargo", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Domain.Entities.Ciudad", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Domain.Entities.Compra", b =>
                {
                    b.Navigation("MedicamentoCompras");
                });

            modelBuilder.Entity("Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("Domain.Entities.Empleado", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Domain.Entities.Eps", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Domain.Entities.Medicamento", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("MedicamentoCompras");

                    b.Navigation("MedicamentoVentas");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Domain.Entities.Pais", b =>
                {
                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UsuarioDeEmpleado");
                });

            modelBuilder.Entity("Domain.Entities.Venta", b =>
                {
                    b.Navigation("MedicamentoVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
